- src/graphql/mutation.js
- src/graphql/query.js
- src/pages/JobApplicationList.js
- src/pages/newJobApplication.js
- Made index page to refresh upon new job addition
- Added deletion feature
- Rearranged graphQL queries into separate files
- Updated buttons style
> enable deletion

- README.md
- src/graphql/mutation.js
- src/pages/JobApplicationList.js
- add mutation to handle update of job application
- add mui dialog form for update feature
- enable edit button with corresponding update feature
- update README with info of the new features
> allow update of job application

- README.md
- src/components/JobApplicationDialog.jsx
- src/components/ProfileDialog.jsx
- src/components/SearchBar.jsx
- src/graphql/query.js
- fix profile dialog bug
- update doc
> Single profile

- src/components/JobApplicationList.jsx
- src/components/ProfileDialog.jsx
- make JobApplicationDialog container from md to lg
- remove obsolete CopyButton code from ProfileDialog
> make job container lg

- src/App.js
- src/App.test.js
- src/components/MobileMenu.jsx
- src/components/PrimarySearchAppBar.jsx
- src/components/ProfileDialog.jsx
- src/components/SearchBar.jsx
- src/graphql/query.js
separate searchbar and mobile search bar out
> refactor searchbar

- src/components/Loading.jsx
- src/components/__tests__/Loading.test.jsx
Refactor loading component to give a better UX experience
- to show 3 loading CircularProgress icon in default desktop view
- 2 for small tablet view
- 1 for mobile view
Add unit test
> better loading UX

- src/components/DialogTitleBar.jsx
- src/components/JobApplicationDialog.jsx
- src/components/ProfileDialog.jsx
Better UX experience:
- add background color to Dialog title and make is a resuable component for job application and profile
- blur the background when a modal is popped up for better UX experience
Housekeeping:
- DRY jobApplicationDialog by combining state objects to array
- fix bug (Edit/Add job application will modify the url from the browser address bar after save button is submitted)
work for:
- https://github.com/januschung/job-winner-ui/issues/22
- https://github.com/januschung/job-winner-ui/issues/28
- https://github.com/januschung/job-winner-ui/issues/26
> Colorize dialog title bar and more

- src/components/JobApplicationDialog.jsx
- src/components/forms/InterviewsForm.jsx
- src/components/forms/OfferForm.jsx
- src/graphql/mutation.js
- src/graphql/query.js
For https://github.com/januschung/job-winner-ui/issues/46
However, the delete function is not yet working because backend does not have that feature implemented yet.
> wire interview form functionality

- src/components/forms/InterviewsForm.jsx
- src/components/forms/OfferForm.jsx
For https://github.com/januschung/job-winner-ui/issues/48
- update layout to be responsive
- replace deleteicon with button
- add confirm dialog and snackbar
> update UX for offer form

- .github/workflows/deploy.yml
- .github/workflows/node.js.yml
set up workflow to deploy new change to demo server automatically
> deploy workflow

- .github/workflows/deploy.yml
- src/components/ProfileDialog.jsx
- remove wording from profile dialog per feedback
- make deploy workflow only run after merging to main
for https://github.com/januschung/job-winner-ui/issues/76
> remove hint wording from profile

- src/components/FrequentUrlContent.jsx
- src/components/JobApplicationList.jsx
- src/components/QuestionContent.jsx
- src/components/__tests__/JobApplicationList.test.jsx
- src/components/common/ActionIcons.jsx
- src/components/common/__tests__/ActionIcons.test.jsx
For https://github.com/januschung/job-winner-ui/issues/71
Move the icon group into a common element and refactor existing usage. Add unit tests too.
> small icons to replace buttons

- src/components/AddOrEditFrequentUrlDialog.jsx
- src/components/AddOrEditQuestionDialog.jsx
- src/components/FrequentUrlDialog.jsx
- src/components/InterviewListDialog.jsx
- src/components/JobApplicationDialog.jsx
- src/components/JobApplicationList.jsx
- src/components/OfferListDialog.jsx
- src/components/ProfileDialog.jsx
- src/components/QuestionDialog.jsx
- src/components/common/CustomDialog.jsx
- create resuable dialog component
- refactor existing dialogs to use the new resuable dialog component
> refactor all dialogs

- src/components/AppHeader.jsx
- src/components/MobileMenu.jsx
close https://github.com/januschung/job-winner-ui/issues/86
> add mobile menu for dark mode

- src/components/JobApplicationList.jsx
- src/components/common/ActionIcons.jsx
close https://github.com/januschung/job-winner-ui/issues/70
- remove the dedicate link field
- make the company name a hyperlink to the job posting
> remove link field

- src/components/FrequentUrlContent.jsx
- src/components/QuestionContent.jsx
close https://github.com/januschung/job-winner-ui/issues/90
> replace generic loading with skeletons

- src/components/__tests__/JobApplicationList.test.jsx
- src/components/forms/ApplicationForm.jsx
- src/graphql/mutation.js
- src/graphql/query.js
close https://github.com/januschung/job-winner-ui/issues/74
- add note field to job application form
- update graphql query and also fix the bug that broke new application creation
> add note field to job application

- src/components/JobApplicationList.jsx
- src/components/JobStatusBar.jsx
- src/config/statusColor.js
close https://github.com/januschung/job-winner-ui/issues/18 https://github.com/januschung/job-winner-ui/issues/73
- introduce a status bar to show all and different job application status counts
- it also work to filter out job by status
- move status color setting to a config file
> add status bar

- src/components/JobApplicationList.jsx
- src/components/__tests__/JobApplicationDialog.test.jsx
- src/components/forms/ApplicationForm.jsx
close https://github.com/januschung/job-winner-ui/issues/75
- remove status from new job application
- remove status from job card now that we have filtering and a color legend as reference
- updatet some styling
- add Ghosted status
> remove status

- .github/workflows/deploy.yml
- README.md
close https://github.com/januschung/job-winner-ui/issues/98
> update deploy workflow

- src/components/AppHeader.jsx
- src/components/ProfileDialog.jsx
close https://github.com/januschung/job-winner-ui/issues/96
- show snackbar with successful color the save button is clicked
- it will not close the modal any more upon saving
> show snackbar after profile is saved

- Dockerfile
- src/graphql/mutation.js
close https://github.com/januschung/job-winner-ui/issues/104
- fix graphql query for adding interview
- update Dockerfile to work with vite migration
> fix add interview bug

- src/components/AppHeader.jsx
close https://github.com/januschung/job-winner-ui/issues/106
> github link

- .env
- .github/workflows/deploy.yml
- Dockerfile
- README.md
- entrypoint.sh
- index.html
- public/config.template.js
- src/index.jsx
close https://github.com/januschung/job-winner-ui/issues/117
> set backend url dynamically by env var

- .github/workflows/ghcr.yml
close https://github.com/januschung/job-winner-ui/issues/117
> build and push to ghcr

- src/components/JobApplicationList.jsx
close https://github.com/januschung/job-winner-ui/issues/118
> make ghosted status in the sorting logic

- src/components/ProfileDialog.jsx
- src/graphql/mutation.js
- src/graphql/query.js
close https://github.com/januschung/job-winner-ui/issues/111
> new profile fields

- .github/workflows/ghcr.yml
close https://github.com/januschung/job-winner-ui/issues/129
> build arm image
